version: "3"
services:
  postgres-todo:
    image: postgres:9.6
    container_name: postgrestodo
    volumes:
      - ./postgres_data:/usr/local/var/postgres/
    environment:
      - POSTGRES_USER=bon
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  grpc-go-todo:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - .:/grpc_api_todolist
    ports:
      - 8300:8300
    entrypoint: bash -c "./deployment/migrate.sh & go mod download"
    depends_on:
      - postgres-todo
    env_file:
      - deployment/local.env
volumes:
    postgres_data:      
  
  